### ISSUE TITLE
PR: Wrong font inherited by dropdown item text

### ISSUE THREAD

**Issue by stockmind** [Crazyht/ngx-tree-select#137]
Hi, i've made a pullrequest to fix the wrong font inherited by dropdown items text due to the `<i class="fa">` that encapsulate it.

I post it here as it risk to be buried by all the pull requests of greenkeeper bot.
Pull request #135 

Also a class like "item-text" could maybe help developers to target it with css selectors, as by now is hard to select only the item text.

**Comment by Crazyht** [comment]
Released in 0.14.0
