### ISSUE TITLE
How to spread tree

### ISSUE THREAD

**Issue by sevennights** [Crazyht/ngx-tree-select#18]
i want to spread tree.
Is there a property to expand the tree?

**Comment by Crazyht** [comment]
Hi, 

Today, it' not possible. You want expand all the tree at start or only parent where selected child ?

**Comment by sevennights** [comment]
yes , i want to spread the tree  default

**Comment by Crazyht** [comment]
Ok try add ExpandMode with somthing like : 
- None (actual mode)
- Selected
- All

**Comment by Crazyht** [comment]
This feature is in next release.
