### ISSUE TITLE
How should I open the drop down menu?

### ISSUE THREAD

**Issue by jiazijing** [Crazyht/ngx-tree-select#27]
I just follow the demo write the same code and install all the modules, but i can not open the drop down menu.
After i check the git log i found there is a log 'fix: Dropdown no open when click on tree-select', but i don't know if it build in version 0.11.1.
is there a way to use this fixed version? or when you release the new version?

**Comment by Crazyht** [comment]
This fix is already deploy : [CHANGELOG.md](https://github.com/Crazyht/ngx-tree-select/blob/master/CHANGELOG.md)

You have error on console ?

**Comment by jiazijing** [comment]
I found the reason:
If i link `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">`
the drop down will not show.
If i link `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">`
it works good.
In my project there is some 3rd lib depend on 4.0.0-alpha.6, could you support that?

**Comment by Crazyht** [comment]
Hmmm open class is renamed to show. 
Just add show class fix open/close but carret still hidden and multiple select is too big, probably some other fix needed.

**Comment by Thorski** [comment]
I am also stuck with this issue.   Is there a workaround?

Thanks.

**Comment by Crazyht** [comment]
Released in 0.12.0

**Comment by johnenosh92** [comment]
Is this updated? as I still have to add : <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
only after adding the above, the dropdown seems to works. but my whole app is developed on bootstrap 4
how do i deal with this??
