### ISSUE TITLE
Using SystemJs

### ISSUE THREAD

**Issue by andrealegrottaglie** [Crazyht/ngx-tree-select#50]
Hello ,
i would like to use ngx-tree-select  with systemjs but after installing in the bundle directory the  file  ngx-tree-select.umd.min.js is not present.

Please help me.

**Comment by Crazyht** [comment]
Hi, 

I don't use SystemJS personaly but I think you can use "ngx-tree-select.rollup.umd.min.js" in bundle folder.

let me know if it's ok, I upade readme.

**Comment by andrealegrottaglie** [comment]
It's ok tanks
