### ISSUE TITLE
Disable autocomplete on input

### ISSUE THREAD

**Issue by slavede** [Crazyht/ngx-tree-select#52]
Because it doesn't have autocomplete turned off this can happen:

![image](https://user-images.githubusercontent.com/2838038/32163410-80ab6d2c-bd5c-11e7-8e23-771735a84f07.png)

See how 'oth' autocomplete is over Dropdown where I have 'Other' option to select. By turning off autocomplete I believe this would go away.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by Crazyht** [comment]
Released in 0.12.0

**Comment by slavede** [comment]
Is this version published? Last tag I see is 0.10.0

**Comment by Crazyht** [comment]
Latest is 0.12.0

**Comment by Crazyht** [comment]
https://www.npmjs.com/package/ngx-tree-select

**Comment by slavede** [comment]
I see...but while checking github, when you browse tags, you don't see one for that version. I guess you didn't push that tag, only published it on npm

**Comment by Crazyht** [comment]
Ho I forget push tag ^^ 

Lastest published version is always available as master branch.

Thx

**Comment by slavede** [comment]
Glad we sorted it out :)
